seeder:
  file: ./seeder/seeder.rb
  disabled: true
parsers:
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: true
  - page_type: details
    file: ./parsers/details.rb
    disabled: true
exporters:
  - file: ./exporters/products_last10_json.yaml
    disabled: false
  - file: ./exporters/products_json.yaml
    disabled: false
  - file: ./exporters/products_csv.yaml
    disabled: false