seeder:
  file: ./seeder/seeder.rb
  disabled: false
parsers:
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: false
  - page_type: details
    file: ./parsers/details.rb
    disabled: false
  - page_type: browser_page
    file: ./parsers/browser_page.rb
    disabled: false
exporters:
  - file: ./exporters/products_last10_json.yaml
    disabled: false
  - file: ./exporters/products_json.yaml
    disabled: false
  - file: ./exporters/products_csv.yaml
    disabled: false
  - file: ./exporters/bad_offset.yaml
    disabled: false
  - file: ./exporters/bad_collection.yaml
    disabled: false
  - file: ./exporters/json_exclusion.yaml
    disabled: false
finisher:
  file: ./finisher/finisher.rb
